import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

interface Commit {
  hash: string;
  short: string;
  date: string;
  subject: string;
}

interface Milestone {
  label: string;
  match: string;
  evidence: string[];
}

const root = process.cwd();
const outPath = path.join(root, "reports/build_provenance.md");

function run(command: string, args: string[]): string {
  return execFileSync(command, args, {
    cwd: root,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"]
  }).trim();
}

function parseCommits(): Commit[] {
  const output = run("git", ["log", "--reverse", "--pretty=format:%H%x09%h%x09%cI%x09%s"]);
  return output
    .split(/\r?\n/)
    .filter(Boolean)
    .map((line) => {
      const [hash, short, date, ...subjectParts] = line.split("\t");
      return { hash, short, date, subject: subjectParts.join("\t") };
    });
}

function exists(relativePath: string): boolean {
  return fs.existsSync(path.join(root, relativePath));
}

function isShallowRepository(): boolean {
  try {
    return run("git", ["rev-parse", "--is-shallow-repository"]) === "true";
  } catch {
    return false;
  }
}

const commits = parseCommits();
const shallowRepository = isShallowRepository();

const milestones: Milestone[] = [
  {
    label: "Initial Qwen Track 4 submission workspace",
    match: "Prepare AegisOps Qwen hackathon submission",
    evidence: ["README.md", "reports/brief.md", "submissions/devpost_fields.md"]
  },
  {
    label: "Runnable public demo path",
    match: "Enable GitHub Pages workflow deployment",
    evidence: [".github/workflows/pages.yml", "docs/PUBLISHING.md"]
  },
  {
    label: "Judge quickstart and rubric mapping",
    match: "Add rubric scorecard for judges",
    evidence: ["docs/JUDGE_QUICKSTART.md", "docs/RUBRIC_SCORECARD.md"]
  },
  {
    label: "Alibaba deployment proof path",
    match: "Add Alibaba ECS deployment pack",
    evidence: ["infra/alibaba/DEPLOYMENT.md", "infra/alibaba/deploy-acr-ecs.sh", "scripts/verifyAlibabaDeployment.ts"]
  },
  {
    label: "Qwen integration audit",
    match: "Add Qwen integration audit",
    evidence: ["reports/qwen_integration_audit.md", "scripts/qwenIntegrationAudit.ts"]
  },
  {
    label: "Qwen Function Calling tools",
    match: "Add Qwen function tool schemas",
    evidence: ["docs/QWEN_TOOLS.md", "src/server/agent/toolRegistry.ts", "agents/aegisops/openapi.yaml"]
  },
  {
    label: "Live Qwen tool-call loop",
    match: "Add live Qwen tool call loop",
    evidence: ["src/server/agent/qwenClient.ts", "src/server/agent/orchestrator.ts", "tests/orchestrator.test.ts"]
  },
  {
    label: "Active-incident tool scoping guard",
    match: "Scope Qwen tool calls to active incident",
    evidence: ["src/server/agent/orchestrator.ts", "tests/orchestrator.test.ts", "reports/qwen_integration_audit.md"]
  },
  {
    label: "Visible judge rubric evidence UI",
    match: "Add judge rubric evidence panel",
    evidence: ["src/client/main.tsx", "src/client/styles.css", "docs/RUBRIC_SCORECARD.md"]
  },
  {
    label: "Upload-ready demo video asset evidence",
    match: "Refresh demo video asset evidence",
    evidence: ["docs/demo/aegisops-demo-reel-fixed.mov", "reports/video_asset_audit.md", "scripts/videoAssetAudit.ts"]
  }
];

const milestoneRows = milestones.map((milestone) => {
  const commit = commits.find((candidate) => candidate.subject.includes(milestone.match));
  const missingEvidence = milestone.evidence.filter((relativePath) => !exists(relativePath));
  const status = commit && missingEvidence.length === 0 ? "PASS" : "FAIL";
  return {
    ...milestone,
    commit,
    missingEvidence,
    status
  };
});

const firstCommit = commits[0];
const failures = milestoneRows.filter((row) => row.status === "FAIL");
const milestoneHashes = new Set(
  milestoneRows
    .map((row) => row.commit?.hash)
    .filter((hash): hash is string => Boolean(hash))
);
const milestoneTrail = commits.filter((commit) => milestoneHashes.has(commit.hash));

const lines = [
  "# Build Provenance",
  "",
  "Generated by `pnpm run provenance:audit`.",
  "",
  "This report documents contest-period implementation evidence for the Devpost New & Existing project rule. It is not a claim of prize placement; it is a verifiable build history index.",
  "",
  "## Summary",
  "",
  `- Shallow repository: ${shallowRepository ? "yes" : "no"}`,
  `- First tracked commit: ${firstCommit ? `${firstCommit.short} ${firstCommit.date} ${firstCommit.subject}` : "missing"}`,
  `- Milestones checked: ${milestoneRows.length}`,
  `- Milestone commits found: ${milestoneTrail.length}`,
  `- Failures: ${failures.length}`,
  "",
  "## Milestones",
  "",
  "| status | milestone | commit | evidence |",
  "| --- | --- | --- | --- |",
  ...milestoneRows.map((row) => {
    const commit = row.commit ? `${row.commit.short} ${row.commit.date} ${row.commit.subject}` : "missing";
    const evidence = row.missingEvidence.length
      ? `missing: ${row.missingEvidence.map((entry) => `\`${entry}\``).join("<br>")}`
      : row.evidence.map((entry) => `\`${entry}\``).join("<br>");
    return `| ${row.status} | ${row.label} | ${commit.replaceAll("|", "\\|")} | ${evidence} |`;
  }),
  "",
  "## Milestone Commit Trail",
  "",
  "| commit | date | subject |",
  "| --- | --- | --- |",
  ...milestoneTrail
    .reverse()
    .map((commit) => `| ${commit.short} | ${commit.date} | ${commit.subject.replaceAll("|", "\\|")} |`),
  "",
  "## Claim Boundary",
  "",
  "This report proves the repository contains a substantial, reviewable implementation trail for the submitted Devpost project. Live Alibaba deployment and optional blog publication still require account-owner action.",
  "",
  "## CI Note",
  "",
  "This audit requires enough Git history to find milestone commits. GitHub Actions uses `actions/checkout` with `fetch-depth: 0` for CI and Pages so the provenance check remains reproducible.",
  ""
];

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");

if (failures.length > 0) {
  if (shallowRepository) {
    console.error("Build provenance audit is running in a shallow clone. Use actions/checkout with fetch-depth: 0.");
  }
  console.error(failures.map((row) => `${row.label}: ${row.missingEvidence.join(", ") || "missing commit"}`).join("\n"));
  process.exitCode = 1;
} else {
  console.log("build provenance audit passed");
}
console.log(`Wrote ${outPath}`);
