import fs from "node:fs";
import path from "node:path";
import { MemoryStore } from "../src/server/agent/memory";
import { runIncidentWorkflow } from "../src/server/agent/orchestrator";
import { executeAegisTool } from "../src/server/agent/toolRegistry";
import { getAlibabaDeploymentProof } from "../src/server/cloud/alibabaProof";
import type { WorkflowResult } from "../src/server/agent/types";

const outDir = path.resolve(process.cwd(), "reports");
const outPath = path.join(outDir, "judge_demo_transcript.md");

function cell(value: unknown): string {
  return String(value ?? "not provided")
    .replace(/mem-\d+-[a-z0-9]+/g, "mem-generated")
    .replaceAll("|", "\\|")
    .replace(/\r?\n/g, "<br>")
    .trim();
}

function summarizeRun(result: WorkflowResult): string[] {
  return [
    `## ${result.incident.title}`,
    "",
    `- Incident ID: \`${result.incident.id}\``,
    `- Service: \`${result.incident.service}\``,
    `- Severity: \`${result.incident.severity}\``,
    `- Provider mode: \`${result.providerMode}\``,
    `- Model: \`${result.model}\``,
    `- Approval required: ${result.approval.required ? "yes" : "no"}`,
    `- Approval granted: ${result.approval.approved ? "yes" : "no"}`,
    `- Approval reason: ${result.approval.reason}`,
    `- Scorecard overall: ${result.scorecard.overall.toFixed(3)}`,
    "",
    "### Recalled Memories",
    "",
    "| id | score | tags | memory |",
    "| --- | ---: | --- | --- |",
    ...result.memories.map(
      (memory) =>
        `| \`${cell(memory.id)}\` | ${Number(memory.score ?? 0).toFixed(3)} | ${memory.tags.map((tag) => `\`${cell(tag)}\``).join(", ")} | ${cell(
          memory.text
        )} |`
    ),
    "",
    "### Tool Calls",
    "",
    "| tool | risk | summary |",
    "| --- | --- | --- |",
    ...result.toolCalls.map(
      (tool) => `| \`${cell(tool.name)}\` | ${tool.risk} | ${cell(tool.output.summary)} |`
    ),
    "",
    "### Agent Council",
    "",
    "| agent | confidence | stance | objections |",
    "| --- | ---: | --- | --- |",
    ...result.findings.map(
      (finding) =>
        `| \`${cell(finding.agent)}\` | ${finding.confidence.toFixed(2)} | ${cell(finding.stance)} | ${cell(
          finding.objections.join("; ") || "none"
        )} |`
    ),
    "",
    "### Plan And Verification",
    "",
    `- Plan: ${result.plan.summary}`,
    `- Actions: ${result.plan.actions.map((action) => `${action.id}:${action.reversible ? "reversible" : "not-reversible"}`).join(", ")}`,
    `- Verification: ${result.plan.verification.join("; ")}`,
    `- Rollback: ${result.plan.rollback.join("; ")}`,
    "",
    "### Timeline",
    "",
    "| phase | summary | detail |",
    "| --- | --- | --- |",
    ...result.timeline.map((event) => `| \`${cell(event.phase)}\` | ${cell(event.summary)} | ${cell(event.detail)} |`),
    ""
  ];
}

const memoryStore = new MemoryStore(undefined, false);
const approvedRun = await runIncidentWorkflow({
  incidentId: "checkout-tax-latency",
  autoApprove: true,
  approver: "judge-transcript",
  memoryStore
});

const blockedRun = await runIncidentWorkflow({
  incidentId: "support-pii-leak-risk",
  autoApprove: false,
  approver: "judge-transcript",
  memoryStore: new MemoryStore(undefined, false)
});

const policyCheck = await executeAegisTool("policy_check", { incidentId: "support-pii-leak-risk" });
const alibabaProof = await getAlibabaDeploymentProof();

const lines = [
  "# Judge Demo Transcript",
  "",
  "Generated by `pnpm run judge:transcript`.",
  "",
  "This report is a deterministic run transcript for judges who want evidence before opening the UI.",
  "",
  "## Summary",
  "",
  "| scenario | approval | providerMode | tools | overall | key result |",
  "| --- | --- | --- | --- | ---: | --- |",
  `| Checkout latency remediation | approved | ${approvedRun.providerMode} | ${approvedRun.toolCalls.length} | ${approvedRun.scorecard.overall.toFixed(
    3
  )} | reversible dry-run generated |`,
  `| Support PII risk | blocked | ${blockedRun.providerMode} | ${blockedRun.toolCalls.length} | ${blockedRun.scorecard.overall.toFixed(
    3
  )} | production mutation held for human approval |`,
  "",
  ...summarizeRun(approvedRun),
  ...summarizeRun(blockedRun),
  "## Direct Tool Evidence",
  "",
  `- Tool: \`${policyCheck.name}\``,
  `- Risk: \`${policyCheck.risk}\``,
  `- Summary: ${policyCheck.output.summary}`,
  `- Recommendation: ${cell(policyCheck.output.recommendation ?? policyCheck.output.summary)}`,
  "",
  "## Alibaba Proof Endpoint Shape",
  "",
  `- Qwen base URL: \`${alibabaProof.qwenBaseUrl}\``,
  `- Qwen model: \`${alibabaProof.qwenModel}\``,
  `- Region: \`${alibabaProof.region}\``,
  `- Compute target: \`${alibabaProof.computeTarget}\``,
  `- Evidence: ${alibabaProof.evidence.join("; ")}`,
  "",
  "No API keys or private runtime values are emitted in this transcript.",
  ""
];

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");
console.log(`Wrote ${outPath}`);
