import fs from "node:fs";
import path from "node:path";
import { listIncidents } from "../src/server/agent/orchestrator";
import { MemoryStore } from "../src/server/agent/memory";
import { fallbackDiagnosis } from "../src/server/agent/qwenClient";
import { listQwenToolSchemas } from "../src/server/agent/toolRegistry";
import type { Incident, ToolCall } from "../src/server/agent/types";

const root = process.cwd();
const outPath = path.join(root, "reports/model_ops_report.md");
const qwenToolSchemas = listQwenToolSchemas();
const qwenToolSchemaTokens = estimateTokens(JSON.stringify(qwenToolSchemas));
const systemPrompt =
  "You are AegisOps, a production incident autopilot. Diagnose conservatively, cite evidence, avoid irreversible actions, and preserve human approval gates.";

function estimateTokens(value: string): number {
  return Math.ceil(value.length / 4);
}

function evidenceTools(incident: Incident): ToolCall[] {
  const critical = incident.signals.filter((signal) => signal.source === "logs" || signal.status === "critical");
  const needsHuman = incident.constraints.some((constraint) => /approval|human|finance|security/i.test(constraint));
  return [
    {
      name: "log_search",
      input: { incidentId: incident.id, service: incident.service },
      output: {
        summary: `${critical.length} correlated log patterns found`,
        excerpts: critical.map((signal) => `${signal.name} -> ${signal.value}`),
        retention: "audit-safe synthetic fixture"
      },
      durationMs: 18,
      risk: "low"
    },
    {
      name: "metric_probe",
      input: { incidentId: incident.id, service: incident.service },
      output: {
        summary: `${incident.service} has ${incident.signals.filter((signal) => signal.status === "critical").length} critical signals`,
        sli: incident.signals.map((signal) => ({
          name: signal.name,
          value: signal.value,
          status: signal.status
        }))
      },
      durationMs: 18,
      risk: "low"
    },
    {
      name: "change_graph",
      input: { incidentId: incident.id, service: incident.service },
      output: {
        summary: `${incident.recentChanges.length} recent changes overlap the alert window`,
        changes: incident.recentChanges,
        likelyChange: incident.recentChanges[0]
      },
      durationMs: 18,
      risk: "low"
    },
    {
      name: "policy_check",
      input: { incidentId: incident.id, service: incident.service },
      output: {
        summary: needsHuman ? "human approval required before production mutation" : "automated action allowed",
        requiredApprovals: incident.constraints.filter((constraint) => /approval|human|finance|security/i.test(constraint)),
        hardStops: incident.constraints.filter((constraint) => /never|no |do not/i.test(constraint))
      },
      durationMs: 18,
      risk: "medium"
    }
  ];
}

const rows = listIncidents().map((incident) => {
  const memories = new MemoryStore(undefined, false).recallForIncident(incident);
  const tools = evidenceTools(incident);
  const userPayload = JSON.stringify(
    {
      incident,
      recalledMemories: memories,
      toolEvidence: tools.map((tool) => tool.output)
    },
    null,
    2
  );
  const fallback = fallbackDiagnosis(incident, tools);
  const inputTokens = estimateTokens(systemPrompt) + estimateTokens(userPayload) + qwenToolSchemaTokens;
  const outputTokens = estimateTokens(fallback);
  return {
    incidentId: incident.id,
    severity: incident.severity,
    qwenRequests: 1,
    evidenceTools: tools.length,
    qwenFunctionTools: qwenToolSchemas.length,
    localToolBudgetMsApprovedPath: 36,
    estimatedInputTokens: inputTokens,
    estimatedOutputTokens: outputTokens,
    estimatedTotalTokens: inputTokens + outputTokens,
    humanApprovalRequired: incident.constraints.some((constraint) => /approval|human|finance|security|never|do not/i.test(constraint))
  };
});

const totalTokens = rows.reduce((sum, row) => sum + row.estimatedTotalTokens, 0);
const maxTokens = Math.max(...rows.map((row) => row.estimatedTotalTokens));

const lines = [
  "# Model Ops Report",
  "",
  "Generated by `pnpm run model:ops`.",
  "",
  "This deterministic report documents model/provider choices, estimated token footprint, latency budget, and failure behavior for judge review. It does not claim live Qwen account spend or production latency.",
  "",
  "## Provider Policy",
  "",
  "| setting | value |",
  "| --- | --- |",
  "| Default provider | Qwen Cloud via DashScope OpenAI-compatible chat completions |",
  "| Default endpoint | `https://dashscope-intl.aliyuncs.com/compatible-mode/v1` |",
  "| Default model | `qwen-plus` |",
  "| Credential env vars | `QWEN_API_KEY`, `DASHSCOPE_API_KEY` |",
  "| Model override | `QWEN_MODEL` |",
  "| Deterministic judge fallback | `QWEN_OFFLINE=1` or missing credentials |",
  "| Strict provider mode | `QWEN_STRICT=1` throws on Qwen provider failure |",
  "| Default provider failure behavior | safe deterministic fallback, preserving approval gates |",
  "| Sampling temperature | `0.2` |",
  "| Function tool schemas | five OpenAI-compatible `tools` definitions sent with `tool_choice=none` |",
  "",
  "## Per-Incident Budget",
  "",
  "| incident | severity | Qwen calls | Qwen tool schemas | evidence tools | local approved-path tool budget | est. input tokens | est. output tokens | est. total tokens | human gate |",
  "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
  ...rows.map(
    (row) =>
      `| ${row.incidentId} | ${row.severity} | ${row.qwenRequests} | ${row.qwenFunctionTools} | ${row.evidenceTools} | ${row.localToolBudgetMsApprovedPath}ms | ${row.estimatedInputTokens} | ${row.estimatedOutputTokens} | ${row.estimatedTotalTokens} | ${row.humanApprovalRequired ? "required" : "policy-auto"} |`
  ),
  "",
  "## Suite Summary",
  "",
  `- Total estimated tokens across deterministic judge incidents: ${totalTokens}`,
  `- Max estimated tokens for one incident run: ${maxTokens}`,
  "- Qwen calls per workflow run: 1",
  `- Function tool schema budget included in each Qwen request: ${qwenToolSchemaTokens} estimated input tokens.`,
  "- Evidence tools before Qwen diagnosis: 4, executed in parallel in the Node workflow.",
  "- Approved remediation adds one dry-run simulator call after the human gate.",
  "",
  "## Cost And Latency Controls",
  "",
  "- One Qwen chat-completions request per incident run; no recursive autonomous model loop.",
  "- Tool outputs are summarized and incident-scoped instead of sending raw private logs.",
  "- Offline fixture mode keeps the same orchestration shape for judges without consuming Qwen credits.",
  "- Qwen provider failure falls back to deterministic diagnosis by default; `QWEN_STRICT=1` is available for environments that prefer hard failure.",
  "- Human approval gates remain active in both Qwen Cloud and fallback modes.",
  "- Local fixture tool delay is budgeted at 18ms per tool; evidence tools run concurrently, and the approved dry-run path budgets 36ms before external Qwen/network latency.",
  ""
];

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");
console.log(`Wrote ${outPath}`);
