import fs from "node:fs";
import path from "node:path";

interface Check {
  name: string;
  status: "PASS" | "FAIL";
  evidence: string;
}

const root = process.cwd();
const outPath = path.join(root, "reports/qwen_integration_audit.md");

function read(relativePath: string): string {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

function includes(relativePath: string, needle: string): boolean {
  return read(relativePath).includes(needle);
}

function add(checks: Check[], name: string, ok: boolean, evidence: string): void {
  checks.push({ name, status: ok ? "PASS" : "FAIL", evidence });
}

const qwenClient = read("src/server/agent/qwenClient.ts");
const orchestrator = read("src/server/agent/orchestrator.ts");
const toolRegistry = read("src/server/agent/toolRegistry.ts");
const mcpServer = read("src/server/mcp/aegisopsMcp.ts");
const openapi = read("agents/aegisops/openapi.yaml");
const manifest = JSON.parse(read("agents/aegisops/cap-manifest.json")) as {
  qwenCloud?: {
    defaultBaseUrl?: string;
    apiKeyEnv?: string[];
  };
  tools?: Array<{ name?: string }>;
  toolSurfaces?: {
    mcp?: { command?: string };
  };
};
const packageJson = JSON.parse(read("package.json")) as { scripts?: Record<string, string> };

const requiredTools = ["log_search", "metric_probe", "change_graph", "policy_check", "remediation_simulator"];
const checks: Check[] = [];

add(
  checks,
  "Qwen Cloud OpenAI-compatible endpoint",
  qwenClient.includes("dashscope-intl.aliyuncs.com/compatible-mode/v1") &&
    qwenClient.includes("/chat/completions") &&
    manifest.qwenCloud?.defaultBaseUrl === "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
  "Qwen client and manifest point at DashScope/Qwen OpenAI-compatible chat completions"
);

add(
  checks,
  "Qwen credential environment variables",
  qwenClient.includes("QWEN_API_KEY") &&
    qwenClient.includes("DASHSCOPE_API_KEY") &&
    (manifest.qwenCloud?.apiKeyEnv ?? []).includes("QWEN_API_KEY") &&
    (manifest.qwenCloud?.apiKeyEnv ?? []).includes("DASHSCOPE_API_KEY"),
  "Supports QWEN_API_KEY and DASHSCOPE_API_KEY without committing secrets"
);

add(
  checks,
  "Deterministic offline judging mode",
  qwenClient.includes("offline-fixture") && qwenClient.includes("QWEN_OFFLINE"),
  "Judges can run the same orchestration path without private Qwen credentials"
);

add(
  checks,
  "Five custom incident tools in manifest",
  requiredTools.every((tool) => manifest.tools?.some((entry) => entry.name === tool)),
  requiredTools.join(", ")
);

add(
  checks,
  "OpenAPI exposes all incident tools",
  requiredTools.every((tool) => openapi.includes(`/api/tools/${tool}`)),
  "agents/aegisops/openapi.yaml exposes the HTTP tool surface"
);

add(
  checks,
  "Qwen request body carries function tool schemas",
  qwenClient.includes("requestBody.tools") &&
    qwenClient.includes("tool_choice") &&
    toolRegistry.includes("listQwenToolSchemas") &&
    requiredTools.every((tool) => toolRegistry.includes(`name: "${tool}"`)) &&
    orchestrator.includes("listQwenToolSchemas()"),
  "src/server/agent/qwenClient.ts sends OpenAI-compatible tools from src/server/agent/toolRegistry.ts"
);

add(
  checks,
  "Qwen Function Calling loop executes model-selected tools",
  qwenClient.includes("tool_calls") &&
    qwenClient.includes('role: "tool"') &&
    qwenClient.includes("toolExecutor") &&
    orchestrator.includes("toolChoice: \"auto\"") &&
    orchestrator.includes("executeAegisTool"),
  "Qwen live mode can receive tool_calls, execute incident-scoped tools, append role=tool output, and ask Qwen for the final response"
);

add(
  checks,
  "MCP stdio exposes list and call methods",
  mcpServer.includes("tools/list") &&
    mcpServer.includes("tools/call") &&
    manifest.toolSurfaces?.mcp?.command === "pnpm run mcp:stdio",
  "src/server/mcp/aegisopsMcp.ts implements initialize, tools/list, and tools/call"
);

add(
  checks,
  "CI covers MCP and Qwen integration audit",
  packageJson.scripts?.["smoke:mcp"] === "tsx scripts/mcpSmoke.ts" &&
    packageJson.scripts?.["qwen:audit"] === "tsx scripts/qwenIntegrationAudit.ts" &&
    includes("scripts/release_check.sh", "pnpm run qwen:audit"),
  "release check includes MCP smoke and Qwen integration audit"
);

const failures = checks.filter((check) => check.status === "FAIL");
const lines = [
  "# Qwen Integration Audit",
  "",
  "Generated by `pnpm run qwen:audit`.",
  "",
  "## Summary",
  "",
  `- Checks: ${checks.length}`,
  `- Failures: ${failures.length}`,
  "",
  "## Checks",
  "",
  "| status | check | evidence |",
  "| --- | --- | --- |",
  ...checks.map((check) => `| ${check.status} | ${check.name} | ${check.evidence.replaceAll("|", "\\|")} |`),
  "",
  "## Judge-Relevant Claim",
  "",
  "AegisOps uses Qwen Cloud as the reasoning layer through the DashScope OpenAI-compatible API, sends OpenAI-compatible function tool schemas in the Qwen request body, supports live Qwen tool-call round trips with role=tool outputs, and exposes custom incident tools through both HTTP/OpenAPI and MCP stdio. The offline fixture mode is only a credential-free judging fallback; it preserves the same orchestration path and tool evidence shape.",
  ""
];

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");

if (failures.length > 0) {
  console.error(failures.map((check) => check.name).join("\n"));
  process.exitCode = 1;
} else {
  console.log("qwen integration audit passed");
}
console.log(`Wrote ${outPath}`);
