import fs from "node:fs";
import path from "node:path";

interface EndpointResult {
  path: string;
  status: number;
  ok: boolean;
  body: unknown;
}

const rawTarget = process.argv.slice(2).find((arg) => arg !== "--") ?? process.env.ALIBABA_PROOF_URL ?? process.env.DEPLOYMENT_URL;
const root = process.cwd();
const outPath = path.join(root, "reports/alibaba_deployment_proof.md");

function usage(): never {
  throw new Error("Usage: pnpm run deploy:verify -- https://<your-domain>");
}

function normalizeBaseUrl(input: string | undefined): URL {
  if (!input) usage();
  const withProtocol = /^https?:\/\//i.test(input) ? input : `https://${input}`;
  const url = new URL(withProtocol);
  return new URL(url.origin);
}

async function fetchJson(baseUrl: URL, endpointPath: string): Promise<EndpointResult> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 15_000);
  try {
    const url = new URL(endpointPath, baseUrl);
    const response = await fetch(url, { signal: controller.signal });
    const text = await response.text();
    let body: unknown = text;
    try {
      body = text ? JSON.parse(text) : {};
    } catch {
      // Keep raw body for error reporting.
    }
    return { path: endpointPath, status: response.status, ok: response.ok, body };
  } finally {
    clearTimeout(timer);
  }
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function assertNoSecrets(payload: unknown): void {
  const serialized = JSON.stringify(payload);
  const forbidden = [
    /sk-[A-Za-z0-9_-]{8,}/,
    /DASHSCOPE_API_KEY/i,
    /QWEN_API_KEY/i,
    /ALIBABA_CLOUD_ACCESS_KEY_SECRET/i,
    /ALIYUN_ACCESS_KEY_SECRET/i,
    /access[_-]?key[_-]?secret/i
  ];
  const hit = forbidden.find((pattern) => pattern.test(serialized));
  assert(!hit, `proof response appears to expose a secret pattern: ${String(hit)}`);
}

function value(record: Record<string, unknown>, key: string): string {
  const raw = record[key];
  return raw === undefined || raw === null || raw === "" ? "not reported" : String(raw);
}

const baseUrl = normalizeBaseUrl(rawTarget);
const health = await fetchJson(baseUrl, "/api/health");
const proof = await fetchJson(baseUrl, "/api/alibaba/proof");
const tools = await fetchJson(baseUrl, "/api/tools");

for (const result of [health, proof, tools]) {
  assert(result.ok, `${result.path} returned HTTP ${result.status}`);
  assertNoSecrets(result.body);
}

const healthBody = asRecord(health.body);
assert(healthBody.ok === true, "/api/health did not report ok=true");
assert(healthBody.app === "aegisops-autopilot", "/api/health did not identify aegisops-autopilot");

const proofBody = asRecord(proof.body);
const computeTarget = String(proofBody.computeTarget ?? "");
assert(computeTarget !== "" && computeTarget !== "local-dev", "/api/alibaba/proof still reports local-dev");
assert(String(proofBody.qwenBaseUrl ?? "").includes("dashscope"), "/api/alibaba/proof did not report DashScope/Qwen base URL");
assert(String(proofBody.qwenModel ?? "").length > 0, "/api/alibaba/proof did not report Qwen model");

const toolsBody = asRecord(tools.body);
const toolList = Array.isArray(toolsBody.tools) ? toolsBody.tools : [];
assert(toolList.length >= 5, "/api/tools did not expose the expected tool surface");

const endpointRows = [health, proof, tools]
  .map((result) => `| ${result.path} | ${result.status} | ${result.ok ? "pass" : "fail"} |`)
  .join("\n");

const lines = [
  "# Alibaba Deployment Proof",
  "",
  "Generated by `pnpm run deploy:verify`.",
  "",
  "## Summary",
  "",
  `- Base URL: ${baseUrl.origin}`,
  `- Compute target: ${computeTarget}`,
  `- Region: ${value(proofBody, "region")}`,
  `- Qwen base URL: ${value(proofBody, "qwenBaseUrl")}`,
  `- Qwen model: ${value(proofBody, "qwenModel")}`,
  `- ECS instance ID: ${value(proofBody, "ecsInstanceId")}`,
  `- Function Compute name: ${value(proofBody, "functionName")}`,
  `- Tool count: ${toolList.length}`,
  "- Secret scan: endpoint responses did not expose Qwen or Alibaba credential patterns",
  "",
  "## Endpoint Checks",
  "",
  "| endpoint | HTTP status | result |",
  "| --- | ---: | --- |",
  endpointRows,
  "",
  "## Devpost Paste",
  "",
  "```text",
  `Live Alibaba proof endpoint: ${new URL("/api/alibaba/proof", baseUrl).toString()}`,
  "```",
  ""
];

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");
console.log(`Verified Alibaba deployment: ${baseUrl.origin}`);
console.log(`Wrote ${outPath}`);
