import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

interface Check {
  name: string;
  status: "PASS" | "WARN" | "FAIL";
  evidence: string;
}

const root = process.cwd();
const outPath = path.join(root, "reports/video_asset_audit.md");

const videoPath = "docs/demo/aegisops-demo-reel-fixed.mov";
const captionsPath = "docs/demo/aegisops-demo-reel-fixed.en.srt";
const submissionPath = "docs/VIDEO_SUBMISSION.md";
const metadataPath = "docs/VIDEO_UPLOAD_METADATA.md";
const scriptPath = "scripts/record_demo.sh";
const frameDir = "docs/demo/frames/reel";
const frameCaptureScriptPath = "scripts/captureDemoFrames.mjs";
const frameRenderScriptPath = "scripts/imageSequenceToVideo.swift";

function fullPath(relativePath: string): string {
  return path.join(root, relativePath);
}

function read(relativePath: string): string {
  return fs.existsSync(fullPath(relativePath)) ? fs.readFileSync(fullPath(relativePath), "utf8") : "";
}

function safeDurationSeconds(relativePath: string): number | undefined {
  try {
    const output = execFileSync("mdls", ["-raw", "-name", "kMDItemDurationSeconds", fullPath(relativePath)], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"]
    }).trim();
    const value = Number.parseFloat(output);
    return Number.isFinite(value) ? value : undefined;
  } catch {
    return undefined;
  }
}

function add(checks: Check[], name: string, ok: boolean, evidence: string, warn = false): void {
  checks.push({ name, status: ok ? "PASS" : warn ? "WARN" : "FAIL", evidence });
}

const checks: Check[] = [];

const videoExists = fs.existsSync(fullPath(videoPath));
const videoSize = videoExists ? fs.statSync(fullPath(videoPath)).size : 0;
add(checks, "Upload video exists", videoExists, videoExists ? `${videoPath} ${videoSize} bytes` : `${videoPath} missing`);
add(checks, "Upload video is current-size final", videoSize >= 5_000_000, `${videoSize} bytes`);

const duration = safeDurationSeconds(videoPath);
if (duration === undefined) {
  checks.push({ name: "Upload video duration", status: "WARN", evidence: "duration unavailable on this platform; macOS mdls provides this locally" });
} else {
  add(checks, "Upload video duration", duration >= 59 && duration < 180, `${duration.toFixed(1)} seconds`);
}

const captions = read(captionsPath);
add(checks, "Captions include rubric slide", captions.includes("30/30/25/15 rubric"), captionsPath);
add(checks, "Captions fit generated duration", captions.includes("00:00:59,500"), captionsPath);

const submission = read(submissionPath);
add(checks, "Submission pack says 59.5 seconds", submission.includes("59.5 seconds"), submissionPath);
add(checks, "Submission pack lists rubric evidence", submission.includes("official 30/30/25/15 rubric evidence"), submissionPath);

const metadata = read(metadataPath);
add(checks, "Upload chapters include rubric evidence", metadata.includes("00:36 Judge rubric evidence"), metadataPath);
add(checks, "Upload chapters include Alibaba proof", metadata.includes("00:54 Alibaba deployment proof endpoint"), metadataPath);

const recordScript = read(scriptPath);
add(checks, "Recording script defaults to 65 seconds", recordScript.includes("DEMO_REEL_SECONDS:-65"), scriptPath);
add(checks, "Recording script supports custom URL", recordScript.includes("DEMO_REEL_URL"), scriptPath);

const frameFiles = fs.existsSync(fullPath(frameDir))
  ? fs.readdirSync(fullPath(frameDir)).filter((name) => /^slide-\d{2}\.png$/.test(name))
  : [];
add(checks, "Seven clean source frames exist", frameFiles.length === 7, `${frameDir}: ${frameFiles.length} frames`);
add(checks, "Frame capture script exists", fs.existsSync(fullPath(frameCaptureScriptPath)), frameCaptureScriptPath);
add(checks, "Frame render script exists", fs.existsSync(fullPath(frameRenderScriptPath)), frameRenderScriptPath);

const failures = checks.filter((check) => check.status === "FAIL");
const warnings = checks.filter((check) => check.status === "WARN");

const lines = [
  "# Video Asset Audit",
  "",
  "Generated by `pnpm run video:audit`.",
  "",
  "## Summary",
  "",
  `- Pass: ${checks.filter((check) => check.status === "PASS").length}`,
  `- Warn: ${warnings.length}`,
  `- Fail: ${failures.length}`,
  "",
  "## Checks",
  "",
  "| status | check | evidence |",
  "| --- | --- | --- |",
  ...checks.map((check) => `| ${check.status} | ${check.name} | ${check.evidence.replaceAll("|", "\\|")} |`),
  "",
  "## Claim Boundary",
  "",
  "This audit verifies the local video asset, captions, chapter metadata, public YouTube upload metadata, and recording script are internally consistent. The submitted Devpost page embeds https://youtu.be/eAqfwJn9sr8.",
  ""
];

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");

if (failures.length > 0) {
  console.error(failures.map((check) => `${check.name}: ${check.evidence}`).join("\n"));
  process.exitCode = 1;
} else {
  console.log("video asset audit passed");
}
console.log(`Wrote ${outPath}`);
